services:
  - type: web
    name: beautypro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn beautypro.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: beautypro.settings